version: '3.8'
services:
  app:
    build: .
    container_name: funny-recipes-app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo:6.0
    container_name: funny-recipes-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongo-data:
